function result = run_parfor_task(task, n_sub, batch_size, jm_data_path, ...
        linearly_2d, nj_lin, nm_lin, I1_vals, I2_vals, P)
% parfor body를 별도 함수로 분리 — 함수 내 parfor의 소스 파일 접근 문제 우회

    g_idx = ceil(task / n_sub);

    [particle_t, laser_t] = init_particles(jm_data_path, batch_size, ...
        P.x_position_fwhm, P.Dye_sigma, P.Dye_tau, ...
        P.vx_caused_tilted, P.x_init_vel_sigma, P.y_init_vel_sigma, ...
        P.z_init_vel_off,   P.z_init_vel_sigma, ...
        P.Ij_distribution,  P.Ips_z, P.Ips_y);

    j_idx_t = particle_t(:,10) + 1;
    m_idx_t = particle_t(:,11) + 1;
    aligned_cost_t = linearly_2d(sub2ind([nj_lin, nm_lin], j_idx_t, m_idx_t), :);

    I1_t = repmat(I1_vals(g_idx), batch_size, 1);
    I2_t = repmat(I2_vals(g_idx), batch_size, 1);

    result = time_integrate( ...
        particle_t(:,1:3), particle_t(:,4:6), ...
        laser_t(:,3),      laser_t(:,4:5), ...
        I1_t, I2_t, aligned_cost_t, zeros(batch_size, 2), ...
        P.lambda, P.w0z, P.w0y, P.tau, batch_size, P.tstep, P.t_ini, P.tend, false);

end
